global:
  scrape_interval: 15s  # Temps entre chaque scrapping

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.50.4:9090']

  - job_name: 'eventsproject'
    static_configs:
      - targets: ['eventsproject:8089']
    metrics_path: '/events/actuator/prometheus'  # Point d'exposition des métrique0s

  - job_name: 'jenkins'
    static_configs:
      - targets: ['192.168.50.4:8080']
    metrics_path: '/prometheus'